In [17]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing
import re

In [92]:
df = pd.read_csv(r'./properati_train.csv')

In [93]:
df.state_name.unique()

array(['Capital Federal', 'Buenos Aires Costa Atlántica',
       'Bs.As. G.B.A. Zona Norte', 'Córdoba', 'Bs.As. G.B.A. Zona Oeste',
       'Bs.As. G.B.A. Zona Sur', 'Santa Fe', 'Misiones', 'Entre Ríos',
       'Buenos Aires Interior', 'Neuquén', 'Río Negro', 'Mendoza',
       'Corrientes', 'Chubut', 'Salta', 'Tucumán', 'Chaco', 'San Luis',
       'Tierra Del Fuego', 'Catamarca', 'Santa Cruz', 'La Pampa',
       'Santiago Del Estero', 'Jujuy', 'San Juan', 'La Rioja', 'Formosa'],
      dtype=object)

In [105]:
data = df[['price_usd_per_m2','state_name','property_type','surface_total_in_m2','new_rooms_clean','place_name_clean','surface_total_in_m2_clean','state_name']]

In [106]:
data['log_price'] = np.log(data['price_usd_per_m2'])
data['log_superficie'] = np.log(data['surface_total_in_m2_clean'])

C:\Users\Francesco\Anaconda3\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\Francesco\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\Francesco\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [107]:
print(min(data['price_usd_per_m2']),max(data['price_usd_per_m2']))

0.6 206333.33333333328

In [108]:
data.price_usd_per_m2.quantile([0.25,0.5,0.75])

0.25    1218.181818
0.50    1800.000000
0.75    2486.411765
Name: price_usd_per_m2, dtype: float64

In [109]:
lista = []
for i in data['price_usd_per_m2']:
    if i <=1800:
        lista.append(str('bajo'))
    elif i> 1800 and i<= 2486:
        
        lista.append(str('medio'))
    else:
        i > 2486.41
        lista.append(str('alto'))

In [110]:
data['barrios_category'] = lista

C:\Users\Francesco\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [111]:
data = pd.get_dummies(data = data, columns = ['barrios_category','property_type'], drop_first=True)

In [112]:
data.log_price.dropna(inplace=True)

C:\Users\Francesco\Anaconda3\lib\site-packages\pandas\core\series.py:4494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(result)

In [113]:
data.dropna(subset=['log_price'],inplace=True)

In [114]:
data

,price_usd_per_m2,state_name,surface_total_in_m2,new_rooms_clean,place_name_clean,surface_total_in_m2_clean,state_name,log_price,log_superficie,barrios_category_bajo,barrios_category_medio,property_type_apartment,property_type_house,property_type_store
0,1127.272727,Capital Federal,55.0,2.0,Mataderos,55.0,Capital Federal,7.027556,4.007333,1,0,0,0,0
1,1309.090909,Capital Federal,55.0,2.0,Mataderos,55.0,Capital Federal,7.177088,4.007333,1,0,1,0,0
2,1828.571429,Buenos Aires Costa Atlántica,35.0,0.0,Mar del Plata Centro,35.0,Buenos Aires Costa Atlántica,7.511290,3.555348,0,1,1,0,0
3,1226.415094,Bs.As. G.B.A. Zona Norte,106.0,0.0,Munro,106.0,Bs.As. G.B.A. Zona Norte,7.111851,4.663439,1,0,0,0,0
4,3066.666667,Capital Federal,45.0,1.0,Belgrano,45.0,Capital Federal,8.028346,3.806662,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92708,7699.115044,Capital Federal,113.0,0.0,Belgrano,113.0,Capital Federal,8.948861,4.727388,0,0,1,0,0
92709,1383.333333,Bs.As. G.B.A. Zona Norte,360.0,0.0,Beccar,360.0,Bs.As. G.B.A. Zona Norte,7.232251,5.886104,1,0,0,1,0
92710,2858.695652,Capital Federal,46.0,1.0,Villa Urquiza,46.0,Capital Federal,7.958121,3.828641,0,0,1,0,0
92711,1997.916667,Buenos Aires Costa Atlántica,48.0,2.0,Mar del Plata Plaza Colón,48.0,Buenos Aires Costa Atlántica,7.599860,3.871201,0,1,1,0,0
92712,1675.324675,Capital Federal,77.0,0.0,Capital Federal,77.0,Capital Federal,7.423762,4.343805,1,0,1,0,0

In [115]:
data1 = data.query('state_name == "Capital Federal"')

In [116]:
data1 = pd.get_dummies(data = data1, columns = ['place_name_clean','new_rooms_clean'], drop_first=True)

In [117]:
data1.columns

Index(['price_usd_per_m2', 'state_name', 'surface_total_in_m2',
       'surface_total_in_m2_clean', 'state_name', 'log_price',
       'log_superficie', 'barrios_category_bajo', 'barrios_category_medio',
       'property_type_apartment', 'property_type_house', 'property_type_store',
       'place_name_clean_Agronomía', 'place_name_clean_Almagro',
       'place_name_clean_Balvanera', 'place_name_clean_Barracas',
       'place_name_clean_Barrio Norte', 'place_name_clean_Belgrano',
       'place_name_clean_Boca', 'place_name_clean_Boedo',
       'place_name_clean_Caballito', 'place_name_clean_Capital Federal',
       'place_name_clean_Catalinas', 'place_name_clean_Centro / Microcentro',
       'place_name_clean_Chacarita', 'place_name_clean_Coghlan',
       'place_name_clean_Colegiales', 'place_name_clean_Congreso',
       'place_name_clean_Constitución', 'place_name_clean_Flores',
       'place_name_clean_Floresta', 'place_name_clean_Las Cañitas',
       'place_name_clean_Liniers', 'place_name_clean_Mataderos',
       'place_name_clean_Monserrat', 'place_name_clean_Monte Castro',
       'place_name_clean_Nuñez', 'place_name_clean_Once',
       'place_name_clean_Palermo', 'place_name_clean_Palermo Chico',
       'place_name_clean_Palermo Hollywood', 'place_name_clean_Palermo Soho',
       'place_name_clean_Palermo Viejo', 'place_name_clean_Parque Avellaneda',
       'place_name_clean_Parque Centenario',
       'place_name_clean_Parque Chacabuco', 'place_name_clean_Parque Chas',
       'place_name_clean_Parque Patricios', 'place_name_clean_Paternal',
       'place_name_clean_Pompeya', 'place_name_clean_Puerto Madero',
       'place_name_clean_Recoleta', 'place_name_clean_Retiro',
       'place_name_clean_Saavedra', 'place_name_clean_San Cristobal',
       'place_name_clean_San Nicolás', 'place_name_clean_San Telmo',
       'place_name_clean_Tribunales', 'place_name_clean_Velez Sarsfield',
       'place_name_clean_Versalles', 'place_name_clean_Villa Crespo',
       'place_name_clean_Villa Devoto', 'place_name_clean_Villa General Mitre',
       'place_name_clean_Villa Lugano', 'place_name_clean_Villa Luro',
       'place_name_clean_Villa Ortuzar', 'place_name_clean_Villa Pueyrredón',
       'place_name_clean_Villa Real', 'place_name_clean_Villa Riachuelo',
       'place_name_clean_Villa Santa Rita', 'place_name_clean_Villa Soldati',
       'place_name_clean_Villa Urquiza', 'place_name_clean_Villa del Parque',
       'new_rooms_clean_1.0', 'new_rooms_clean_2.0', 'new_rooms_clean_3.0',
       'new_rooms_clean_4.0', 'new_rooms_clean_5.0', 'new_rooms_clean_6.0',
       'new_rooms_clean_7.0', 'new_rooms_clean_8.0', 'new_rooms_clean_9.0',
       'new_rooms_clean_10.0', 'new_rooms_clean_11.0', 'new_rooms_clean_12.0',
       'new_rooms_clean_13.0', 'new_rooms_clean_14.0', 'new_rooms_clean_15.0'],
      dtype='object')

In [118]:
X_caba = data1[['log_superficie','barrios_category_bajo','barrios_category_medio', 'property_type_apartment',
       'property_type_house', 'property_type_store', 'place_name_clean_Agronomía', 'place_name_clean_Almagro',
       'place_name_clean_Balvanera', 'place_name_clean_Barracas',
       'place_name_clean_Barrio Norte', 'place_name_clean_Belgrano',
       'place_name_clean_Boca', 'place_name_clean_Boedo',
       'place_name_clean_Caballito', 'place_name_clean_Capital Federal',
       'place_name_clean_Catalinas', 'place_name_clean_Centro / Microcentro',
       'place_name_clean_Chacarita', 'place_name_clean_Coghlan',
       'place_name_clean_Colegiales', 'place_name_clean_Congreso',
       'place_name_clean_Constitución', 'place_name_clean_Flores',
       'place_name_clean_Floresta', 'place_name_clean_Las Cañitas',
       'place_name_clean_Liniers', 'place_name_clean_Mataderos',
       'place_name_clean_Monserrat', 'place_name_clean_Monte Castro',
       'place_name_clean_Nuñez', 'place_name_clean_Once',
       'place_name_clean_Palermo', 'place_name_clean_Palermo Chico',
       'place_name_clean_Palermo Hollywood', 'place_name_clean_Palermo Soho',
       'place_name_clean_Palermo Viejo', 'place_name_clean_Parque Avellaneda',
       'place_name_clean_Parque Centenario',
       'place_name_clean_Parque Chacabuco', 'place_name_clean_Parque Chas',
       'place_name_clean_Parque Patricios', 'place_name_clean_Paternal',
       'place_name_clean_Pompeya', 'place_name_clean_Puerto Madero',
       'place_name_clean_Recoleta', 'place_name_clean_Retiro',
       'place_name_clean_Saavedra', 'place_name_clean_San Cristobal',
       'place_name_clean_San Nicolás', 'place_name_clean_San Telmo',
       'place_name_clean_Tribunales', 'place_name_clean_Velez Sarsfield',
       'place_name_clean_Versalles', 'place_name_clean_Villa Crespo',
       'place_name_clean_Villa Devoto', 'place_name_clean_Villa General Mitre',
       'place_name_clean_Villa Lugano', 'place_name_clean_Villa Luro',
       'place_name_clean_Villa Ortuzar', 'place_name_clean_Villa Pueyrredón',
       'place_name_clean_Villa Real', 'place_name_clean_Villa Riachuelo',
       'place_name_clean_Villa Santa Rita', 'place_name_clean_Villa Soldati',
       'place_name_clean_Villa Urquiza', 'place_name_clean_Villa del Parque','new_rooms_clean_1.0',
        'new_rooms_clean_2.0', 'new_rooms_clean_3.0',
       'new_rooms_clean_4.0', 'new_rooms_clean_5.0', 'new_rooms_clean_6.0']]
y_caba = data1['log_price']

#spliteamos en set de testeo y entrenamiento
X_train, X_test, y_train, y_test = train_test_split(X_caba, y_caba, test_size=0.30, random_state=10)

In [119]:
lm = linear_model.LinearRegression()

model_1 = lm.fit(X_train, y_train)

y_pred = lm.predict(X_test)

print ('MAE:', metrics.mean_absolute_error(y_test, y_pred))
print ('MSE:', metrics.mean_squared_error(y_test, y_pred))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print ('R2:', metrics.r2_score(y_test, y_pred))
print('Score model_1: test', model_1.score(X_test, y_test))
print('Score model_1: train', model_1.score(X_train, y_train))

MAE: 0.21449402418410102
MSE: 0.11082906096516669
RMSE: 0.33290998928414073
R2: 0.6557018467499207
Score model_1: test 0.6557018467499207
Score model_1: train 0.6738516446494268

In [120]:
lm_lasso = linear_model.LassoCV(alphas=[0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005, 0.01,\
                                        0.05, 0.1, 1, 5, 10, 15, 25, 50,100,200],\
                                        normalize=True, cv=10)

model_3 = lm_lasso.fit(X_train, y_train)
y_pred = lm_lasso.predict(X_test)

print ('MAE:', metrics.mean_absolute_error(y_test, y_pred))
print ('MSE:', metrics.mean_squared_error(y_test, y_pred))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print ('R2:', metrics.r2_score(y_test, y_pred))
print('Score model_3:', model_3.score(X_test,y_test))

MAE: 0.21347901244321785
MSE: 0.11079434304493332
RMSE: 0.33285784209619174
R2: 0.6558097003734824
Score model_3: 0.6558097003734824

In [20]:
lm_ridge = linear_model.RidgeCV(alphas=[0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005, 0.01,\
                                        0.05, 0.1, 1, 5, 10, 25, 50 ],\
                                        normalize=True, cv=5) 
# Definimos el rango de de búsqueda del hiperparametro explicitamente

model_2 = lm_ridge.fit(X_train, y_train)
y_pred = lm_ridge.predict(X_test)
print ('MAE:', metrics.mean_absolute_error(y_test, y_pred))
print ('MSE:', metrics.mean_squared_error(y_test, y_pred))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print ('R2:', metrics.r2_score(y_test, y_pred))
print('Score model_2 test:', model_2.score(X_test, y_test))
print('Score model_2 train:', model_2.score(X_train, y_train))

MAE: 0.21449198502994538
MSE: 0.1108288823083515
RMSE: 0.3329097209580271
R2: 0.6557024017596897
Score model_2 test: 0.6557024017596897
Score model_2 train: 0.6738516436338311

# OPTICA POR PROVINCIA

In [47]:
data

,price_usd_per_m2,state_name,surface_total_in_m2,new_rooms_clean,place_name_clean,surface_total_in_m2_clean,state_name,log_price,log_superficie,barrios_category_bajo,...,property_type_house,property_type_store,baños_final_2,baños_final_3,baños_final_4,baños_final_5,baños_final_6,baños_final_7,baños_final_8,baños_final_9
0,1127.272727,Capital Federal,55.0,2.0,Mataderos,55.0,Capital Federal,7.027556,4.007333,1,...,0,0,0,0,0,0,0,0,0,0
1,1309.090909,Capital Federal,55.0,2.0,Mataderos,55.0,Capital Federal,7.177088,4.007333,1,...,0,0,0,0,0,0,0,0,0,0
2,1828.571429,Buenos Aires Costa Atlántica,35.0,0.0,Mar del Plata Centro,35.0,Buenos Aires Costa Atlántica,7.511290,3.555348,0,...,0,0,0,0,0,0,0,0,0,0
3,1226.415094,Bs.As. G.B.A. Zona Norte,106.0,0.0,Munro,106.0,Bs.As. G.B.A. Zona Norte,7.111851,4.663439,1,...,0,0,0,0,0,0,0,0,0,0
4,3066.666667,Capital Federal,45.0,1.0,Belgrano,45.0,Capital Federal,8.028346,3.806662,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92708,7699.115044,Capital Federal,113.0,0.0,Belgrano,113.0,Capital Federal,8.948861,4.727388,0,...,0,0,0,0,0,0,0,0,0,0
92709,1383.333333,Bs.As. G.B.A. Zona Norte,360.0,0.0,Beccar,360.0,Bs.As. G.B.A. Zona Norte,7.232251,5.886104,1,...,1,0,0,0,0,0,0,0,0,0
92710,2858.695652,Capital Federal,46.0,1.0,Villa Urquiza,46.0,Capital Federal,7.958121,3.828641,0,...,0,0,0,0,0,0,0,0,0,0
92711,1997.916667,Buenos Aires Costa Atlántica,48.0,2.0,Mar del Plata Plaza Colón,48.0,Buenos Aires Costa Atlántica,7.599860,3.871201,0,...,0,0,0,0,0,0,0,0,0,0
92712,1675.324675,Capital Federal,77.0,0.0,Capital Federal,77.0,Capital Federal,7.423762,4.343805,1,...,0,0,0,0,0,0,0,0,0,0

In [48]:
data3 = pd.get_dummies(data = data, columns = ['state_name','new_rooms_clean'], drop_first=True)

In [49]:
data3.columns

Index(['price_usd_per_m2', 'surface_total_in_m2', 'place_name_clean',
       'surface_total_in_m2_clean', 'log_price', 'log_superficie',
       'barrios_category_bajo', 'barrios_category_medio',
       'property_type_apartment', 'property_type_house',
       ...
       'new_rooms_clean_19.0', 'new_rooms_clean_20.0', 'new_rooms_clean_21.0',
       'new_rooms_clean_22.0', 'new_rooms_clean_23.0', 'new_rooms_clean_24.0',
       'new_rooms_clean_25.0', 'new_rooms_clean_27.0', 'new_rooms_clean_30.0',
       'new_rooms_clean_32.0'],
      dtype='object', length=101)

In [24]:
X_caba = data3[['log_superficie','barrios_category_bajo','barrios_category_medio', 'property_type_apartment',
       'property_type_house', 'property_type_store', 'state_name_Bs.As. G.B.A. Zona Oeste',
       'state_name_Bs.As. G.B.A. Zona Sur',
       'state_name_Buenos Aires Costa Atlántica',
       'state_name_Buenos Aires Interior', 'state_name_Capital Federal',
       'state_name_Catamarca', 'state_name_Chaco', 'state_name_Chubut',
       'state_name_Corrientes', 'state_name_Córdoba', 'state_name_Entre Ríos',
       'state_name_Formosa', 'state_name_Jujuy', 'state_name_La Pampa',
       'state_name_La Rioja', 'state_name_Mendoza', 'state_name_Misiones',
       'state_name_Neuquén', 'state_name_Río Negro', 'state_name_Salta',
       'state_name_San Juan', 'state_name_San Luis', 'state_name_Santa Cruz',
       'state_name_Santa Fe', 'state_name_Santiago Del Estero',
       'state_name_Tierra Del Fuego', 'state_name_Tucumán',
       'state_name_Bs.As. G.B.A. Zona Oeste',
       'state_name_Bs.As. G.B.A. Zona Sur',
       'state_name_Buenos Aires Costa Atlántica',
       'state_name_Buenos Aires Interior', 'state_name_Capital Federal',
       'state_name_Catamarca', 'state_name_Chaco', 'state_name_Chubut',
       'state_name_Corrientes', 'state_name_Córdoba', 'state_name_Entre Ríos',
       'state_name_Formosa', 'state_name_Jujuy', 'state_name_La Pampa',
       'state_name_La Rioja', 'state_name_Mendoza', 'state_name_Misiones',
       'state_name_Neuquén', 'state_name_Río Negro', 'state_name_Salta',
       'state_name_San Juan', 'state_name_San Luis', 'state_name_Santa Cruz',
       'state_name_Santa Fe', 'state_name_Santiago Del Estero',
       'state_name_Tierra Del Fuego', 'state_name_Tucumán',
       'new_rooms_clean_1.0', 'new_rooms_clean_2.0', 'new_rooms_clean_3.0',
       'new_rooms_clean_4.0', 'new_rooms_clean_5.0']]
y_caba = data3['log_price']

#spliteamos en set de testeo y entrenamiento
X_train, X_test, y_train, y_test = train_test_split(X_caba, y_caba, test_size=0.30, random_state=1)

In [25]:
lm = linear_model.LinearRegression()

model_1 = lm.fit(X_train, y_train)

y_pred = lm.predict(X_test)

print ('MAE:', metrics.mean_absolute_error(y_test, y_pred))
print ('MSE:', metrics.mean_squared_error(y_test, y_pred))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print ('R2:', metrics.r2_score(y_test, y_pred))
print('Score model_1: test', model_1.score(X_test, y_test))
print('Score model_1: train', model_1.score(X_train, y_train))

MAE: 0.3109252276963568
MSE: 0.20525240786096918
RMSE: 0.45304790901290914
R2: 0.6631382909219905
Score model_1: test 0.6631382909219905
Score model_1: train 0.6693930416672744

In [26]:

lm_lasso = linear_model.LassoCV(alphas=[0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005, 0.01,\
                                        0.05, 0.1, 1, 5, 10, 15, 25, 50,100,200],\
                                        normalize=True, cv=100)

model_3 = lm_lasso.fit(X_train, y_train)
y_pred = lm_lasso.predict(X_test)

print ('MAE:', metrics.mean_absolute_error(y_test, y_pred))
print ('MSE:', metrics.mean_squared_error(y_test, y_pred))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print ('R2:', metrics.r2_score(y_test, y_pred))
print('Score model_3:', model_3.score(X_test,y_test))

MAE: 0.30886594477592516
MSE: 0.20435163183682584
RMSE: 0.45205268701427476
R2: 0.664616650928344
Score model_3: 0.664616650928344

In [87]:
lm_ridge = linear_model.RidgeCV(alphas=[0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005, 0.01,\
                                        0.05, 0.1, 1, 5, 10, 25, 50 ],\
                                        normalize=True, cv=5) 
# Definimos el rango de de búsqueda del hiperparametro explicitamente

model_2 = lm_ridge.fit(X_train, y_train)
y_pred = lm_ridge.predict(X_test)
print ('MAE:', metrics.mean_absolute_error(y_test, y_pred))
print ('MSE:', metrics.mean_squared_error(y_test, y_pred))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print ('R2:', metrics.r2_score(y_test, y_pred))
print('Score model_2 test:', model_2.score(X_test, y_test))
print('Score model_2 train:', model_2.score(X_train, y_train))

MAE: 1.3033017057054792
MSE: 3.530902454304408
RMSE: 1.8790695714380583
R2: 0.615904062980812
Score model_2 test: 0.615904062980812
Score model_2 train: 0.6090883151369162